### ISSUE TITLE
not reloading

### ISSUE THREAD

**Issue by adventmedia** [blaise-io/live-reload#15] opened 2020-02-15 15:43 UTC
Live Reload has suddenly stopped working… possibly due to new Chrome version?
Chrome Version 80.0.3987.106, MacOS 10.14.6

**Comment by blaise-io** [comment] 2020-02-15 16:47
I just released a new Live Reload version, so it’s probably that. I’ll check tomorrow.

**Comment by blaise-io** [comment] 2020-02-15 17:34
Actually I checked just now and it should work, latest stable Chrome and Live Reload, so I need some more information:

Are you using Live Reload 1.8.0?  
Can you show your values of the reload form? 
If possible, can you share the website URL or HTML source?  

You may also get some idea what's going wrong by clicking the "background page" link for Live Reload on the `chrome://extensions/` page.

> ![1](https://i.imgur.com/7hlkJxO.png)

It should show something like this:
> ![2](https://i.imgur.com/fUOayvO.png)

**Comment by adventmedia** [comment] 2020-02-17 20:42
Yes, 1.8.0.
The url is local to my dev environment, http://alm-ng
The console shows logs when I change the rules config, and when I manually reload the page, but nothing when the source updates (angular cli build)

**Comment by Fr3ddy7** [comment] 2020-02-21 02:19
the same problem, 1.8, windows 7, chorme last 

dont reload

**Comment by blaise-io** [comment] 2020-02-22 12:04
@adventmedia @Fr3ddy7 I cannot reproduce the issue. Can you provide the details as requested in https://github.com/blaise-io/live-reload/issues/15#issuecomment-586623209? 

Preferably with html source, screenshot or values of the reload rule and the Live Reload log as shown in my last screenshot.

**Comment by adventmedia** [comment] 2020-02-22 16:49
![_generated_background_page html 2020-02-22 11-48-12](https://user-images.githubusercontent.com/1529172/75096035-3659c000-5569-11ea-9e49-d8ae3d73c317.jpg)

The screen grab shows what I described in my previous message - the console shows logs when I change a setting in the rules config (Reload stylesheets), but nothing when the site builds or rebuilds.
Monitored host is `http://alm-ng/home`

**Comment by Fr3ddy7** [comment] 2020-02-25 23:27
![Screenshot_2](https://user-images.githubusercontent.com/8958344/75296892-224ae280-5837-11ea-95fd-13a5563d6417.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/8958344/75296895-237c0f80-5837-11ea-9209-6353bb8a0f9a.jpg)

**Comment by blaise-io** [comment] 2020-03-26 13:17
@adventmedia you're monitoring *.js but you wanted to monitor stylesheets? (typically *.css)

@adventmedia and @Fr3ddy7 please post **all** relevant data:

 - The full devtools log (this one you did post)
 - The reload rule form
 - The URL of the file that changed but didn't trigger a reload

**Comment by adventmedia** [comment] 2020-03-26 13:31
no, in Angular projects the source css (scss) are compiled into a JavaScript file (styles.js)
reload rules:
- Host URL: `http://alm-ng/*`
- Source file URLs: `http://alm-ng/*.js`
Changed file: `http://alm-ng/main.js`
The odd thing is that one in a blue moon the page does reload, maybe 1 in a 100 times.

**Comment by blaise-io** [comment] 2020-03-26 15:46
@adventmedia can you post a complete devtools log as text that includes polling? if it contains data you don't want to share on the internet you can also send it to blaisekal@gmail.com and I will treat it confidentially.

In your screenshot I cannot see it polling yet, but in your screenshot you also didn't have the `*` at the end of the host URL (so it would only monitor `/` not `/foo/bar`).

**Comment by adventmedia** [comment] 2020-03-26 15:58
I don't know what screen shot you're referring to, but this is the current configuration:
![Update: ALM 2020-03-26 11-57-31](https://user-images.githubusercontent.com/1529172/77667777-067f4d00-6f59-11ea-9b44-37e03461d65d.jpg)
As for the polling, please tell me how to enable or view it.

**Comment by blaise-io** [comment] 2020-03-26 17:49
@adventmedia browse to `chrome://extensions/`, click "background page" for Live Reload, click "Console" (second tab). Now open a new tab in Chrome with the page where you expect source file URLs to refresh the page. Then after a few seconds copy paste the log from the background page. It should display somthing like

```
13 "http://127.0.0.1:3000/" "matches rule" "Reload rule for Live Reload test"
background.js:193 13 "http://127.0.0.1:3000/" "initialize monitoring"
background.js:253 13 "remove webrequests listener"
background.js:183 13 "http://127.0.0.1:3000/" "matches rule" "Reload rule for Live Reload test"
background.js:193 13 "http://127.0.0.1:3000/" "initialize monitoring"
background.js:211 http://127.0.0.1:3000/static/abc/def/style.css SKIP
background.js:587 http://127.0.0.1:3000/static/abc/def/script.js matches /^http://127\.0\.0\.1:3000/.*?\.js$/
background.js:206 http://127.0.0.1:3000/static/abc/def/script.js MATCHED
background.js:211 http://127.0.0.1:3000/pages/frame.html SKIP
background.js:211 http://127.0.0.1:3000/static/abc/def/import.css SKIP
background.js:308 http://127.0.0.1:3000/static/abc/def/script.js not changed
background.js:291 http://127.0.0.1:3000/static/abc/def/script.js change detected
background.js:301 http://127.0.0.1:3000/static/abc/def/script.js reload parent page
```

**Comment by adventmedia** [comment] 2020-03-26 17:57
well, ok, that's what I've been doing, except for "All levels". With "All levels" enabled, here is the result.
```https://use.typekit.net/xvl8djc.js SKIP
background.js:211 https://www.googletagmanager.com/gtag/js?id=UA-7518938-11 SKIP
background.js:587 http://alm-ng/runtime.js matches /^http://alm-ng/.*?\.js$/
background.js:206 http://alm-ng/runtime.js MATCHED
background.js:587 http://alm-ng/styles.js matches /^http://alm-ng/.*?\.js$/
background.js:206 http://alm-ng/styles.js MATCHED
background.js:587 http://alm-ng/main.js matches /^http://alm-ng/.*?\.js$/
background.js:206 http://alm-ng/main.js MATCHED
background.js:587 http://alm-ng/vendor.js matches /^http://alm-ng/.*?\.js$/
background.js:206 http://alm-ng/vendor.js MATCHED
background.js:587 http://alm-ng/polyfills.js matches /^http://alm-ng/.*?\.js$/
background.js:206 http://alm-ng/polyfills.js MATCHED
background.js:587 http://alm-ng/scripts.js matches /^http://alm-ng/.*?\.js$/
background.js:206 http://alm-ng/scripts.js MATCHED
background.js:308 http://alm-ng/runtime.js not changed
background.js:308 http://alm-ng/main.js not changed
background.js:308 http://alm-ng/polyfills.js not changed
background.js:308 http://alm-ng/scripts.js not changed
background.js:308 http://alm-ng/styles.js not changed
background.js:308 http://alm-ng/vendor.js not changed
background.js:211 http://platform.twitter.com/widgets/follow_button.html?screen_name=ALMacraeAuthor&show_count=false SKIP
background.js:211 http://platform.twitter.com/widgets/follow_button.html?screen_name=ALMacraeAuthor&show_count=false&show_screen_name=false SKIP
background.js:253 147 "remove webrequests listener"
background.js:239 147 "http://alm-ng/runtime.js" "stop file monitoring timer"
background.js:239 147 "http://alm-ng/styles.js" "stop file monitoring timer"
background.js:239 147 "http://alm-ng/main.js" "stop file monitoring timer"
background.js:239 147 "http://alm-ng/vendor.js" "stop file monitoring timer"
background.js:239 147 "http://alm-ng/polyfills.js" "stop file monitoring timer"
background.js:239 147 "http://alm-ng/scripts.js" "stop file monitoring timer"
background.js:183 147 "http://alm-ng/home" "matches rule" "ALM"
background.js:193 147 "http://alm-ng/home" "initialize monitoring"
background.js:183 147 "http://alm-ng/home" "matches rule" "ALM"
background.js:253 147 "remove webrequests listener"
background.js:193 147 "http://alm-ng/home" "initialize monitoring"
background.js:211 https://www.google-analytics.com/analytics.js SKIP```

And that's it. No updates as the code changes.

**Comment by blaise-io** [comment] 2020-03-26 19:39
Thanks that’s useful, will have a thorough look tomorrow!

**Comment by blaise-io** [comment] 2020-03-28 11:40
@adventmedia I think I found the problem. https://github.com/blaise-io/live-reload/blob/master/app/background.ts#L32 the tab may trigger the onUpdated when a website uses the History API or when an iframe is loaded. Can you confirm you're doing one or both of these?

**Comment by blaise-io** [comment] 2020-03-28 14:53
Fixed in 1.8.1, currently awaiting review in Chrome, published for Firefox.

[live-reload-1.8.1-chrome.zip](https://github.com/blaise-io/live-reload/files/4397318/live-reload-1.8.1-chrome.zip)

**Closed by blaise-io** 2020-03-28 14:53 UTC

**Comment by adventmedia** [comment] 2020-03-28 15:49
I don't believe I'm using the History api, though that may be buried somewhere inside the Angular framework. Only using iframe on one of the two sites I've been working on.
No matter. The updated version of LiveReload is working just fine, thank you!

**Comment by blaise-io** [comment] 2020-03-29 10:52
Angular's routing uses the History API. 

By the way, Angular also has `ng serve` which should give you auto-reload.

**Comment by adventmedia** [comment] 2020-03-29 14:50
indeed.
I'm using ng build --watch, because my back end is PHP, so I'm using MAMP to run a local domain from /dist. There are other ways of doing this but it's the one I know.
